<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1603" started-at="2018-10-04T15:45:18Z" finished-at="2018-10-04T15:45:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1603" started-at="2018-10-04T15:45:18Z" finished-at="2018-10-04T15:45:19Z">
      <class name="tests.NavBarTest">
        <test-method status="PASS" signature="setupDriverAndPage()[pri:0, instance:tests.NavBarTest@7cd62f43]" name="setupDriverAndPage" is-config="true" duration-ms="6266" started-at="2018-10-04T15:45:11Z" finished-at="2018-10-04T15:45:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriverAndPage -->
        <test-method status="FAIL" signature="checkBatchLink()[pri:1, instance:tests.NavBarTest@7cd62f43]" name="checkBatchLink" duration-ms="1586" started-at="2018-10-04T15:45:18Z" finished-at="2018-10-04T15:45:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://dev-caliber.revature.tech/caliber/#/vp/manage] but found [https://dev-caliber.revature.tech/caliber/#/vp/home]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://dev-caliber.revature.tech/caliber/#/vp/manage] but found [https://dev-caliber.revature.tech/caliber/#/vp/home]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at tests.NavBarTest.checkBatchLink(NavBarTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkBatchLink -->
        <test-method status="PASS" signature="cleanup()[pri:0, instance:tests.NavBarTest@7cd62f43]" name="cleanup" is-config="true" duration-ms="686" started-at="2018-10-04T15:45:19Z" finished-at="2018-10-04T15:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- tests.NavBarTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
